[blob_credentials]
sas_url = "https://epldatapfprdlake.blob.core.windows.net/bicollections?sp=racwdlme&st=2024-01-31T15:09:29Z&se=2026-01-31T23:09:29Z&spr=https&sv=2022-11-02&sr=c&sig=kYyhmQU6%2B%2Bkv5Nf3MsGkB%2Fjq0gyzYBwMs8slQQmsZSg%3D"
